### ISSUE TITLE
Run in docker

### ISSUE THREAD

**Issue by CMBulthuis** [glynnbird/datamaker#19]
Hi Glynn, 
Thanks for this great tool to generate json data :-).

I am trying to integrate it into a docker container and run into an issue. 
My setup to debug the issue is.
Dockerfile:
```
FROM node
#### LABEL mainteiner
WORKDIR /work
RUN npm install -g datamaker
COPY test.json datamaker.sh ./
CMD ["./datamaker.sh"]
```

Script datamaker.sh:
```
#!/usr/bin/env bash

echo "datamaker -t test.json:"
datamaker -t test.json
echo "datamaker -t test.json -f json:"
datamaker -t test.json -f json
```

test.json file:
```
{
  "_id": "{{uuid}}",
  "name": "{{firstname}} {{surname}}",
  "dob": "{{date 2014-01-01}}"
}
```
For building the container I use:
`docker build -t datamaker`
If I run the script in the container from the prompt it works perfect:
```
$ docker run -ti datamaker /bin/bash
root@23e94851a395:/work# ./datamaker.sh 
datamaker -t test.json:
{
  "_id": "R2NF7CJANYQL54XU",
  "name": "Keeley Gatewood",
  "dob": "2020-07-25"
}
datamaker -t test.json -f json:
{"_id":"HAQIOS0RFQPURAUQ","name":"Mariko Foss","dob":"2016-04-18"}
```

When running the container with 'docker run' the first datamaker command does not give output and the second throws an error:
```
$ docker run datamaker
datamaker -t test.json:

datamaker -t test.json -f json:
undefined:1


SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.postCommit (/usr/local/lib/node_modules/datamaker/formatters/json.js:6:30)
    at swap (/usr/local/lib/node_modules/datamaker/index.js:108:20)
    at /usr/local/lib/node_modules/datamaker/index.js:138:22
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
```

Do you have an idea what is causing this behaviour and how to solve it?

Kind regards, Chris

**Comment by glynnbird** [comment]
I'm no Docker expert but `datamaker` definitely runs when you first spin up a container based on the image definition you supply. The problem seems to be when you run it second time round.

I got it working running it like this:

Dockerfile:
```
FROM node
WORKDIR /work
RUN npm install -g datamaker
COPY test.json .
#CMD ["./datamaker.sh"]
```
^ notice that I've got rid of datamaker.sh and no longer run it.

I created the image and ran it with:

```sh
docker run -ti 18ddc3a3f99b datamaker -t test.json -f json
```
where `18ddc3a3f99b` is my image name. It works every time.

A better solution would be to not copy the template into the container but have `/work` be mounted from your local disk.

```sh
docker run -ti 18ddc3a3f99b -v "$PWD":/work datamaker -t test.json
```

where your local test.json file becomes visible to the Docker container via mounting the volume.

**Comment by CMBulthuis** [comment]
Thanks for the quick respons.
In the container I use datamaker to generate test data and send to a Kafka topic.
After receiving the respons the result is evaluated if it is as expected.
So datamaker is not running on its own inside the docker container.
The bash script takes care of the steps to execute.

Do you have any idea's how to get datamaker working in this setup?

**Comment by glynnbird** [comment]
Sorry. I don't know enough about Docker to help. There's nothing special about datamaker. It runs perfectly well inside a container. I would suggest running outside of a container first until you've got your project working, then look at containerising the thing. Docker is just getting in the way imo.

**Comment by CMBulthuis** [comment]
Thans for your help. I will see if I can change the setup for containerising.
